// let options = {
//     method: "POST",

//     headers: { "content-type": "application/json" },

//     body: JSON.stringify({                  // no need to specify 'id', id field in your response will be generated by the server.
//         title: 'games',
//         gameName: 'FreeFire',
//         userID: '1'
//     }),
// };

// let p = fetch("https://jsonplaceholder.typicode.com/posts", options);

// p
//     .then(function (value) {
//         // return value.text();
//         return value.json();
//     })
//     .then(function (value) {
//         console.log(value);
//     })
//     .catch(function (error) {
//         console.log(error);
//     });



/*  ========  OR  ========  */



// let p = fetch("https://jsonplaceholder.typicode.com/posts", {
//     method: "POST",

//     headers: { "content-type": "application/json" },

//     body: JSON.stringify({
//         title: 'games',
//         gameName: 'FreeFire',
//         userID: '1'
//     }),
// });

// p
//     .then(function (value) {
//         // return value.text();
//         return value.json();
//     })
//     .then(function (value) {
//         console.log(value);
//     })
//     .catch(function (error) {
//         console.log(error);
//     }); 




// let options = {
//     method: "POST",

//     headers: { "content-type": "application/json" },

//     body: JSON.stringify({
//         title: 'games',
//         gameName: 'FreeFire',
//         userID: '1'
//     }),
// };

// async function data() {

//     let p = fetch("https://jsonplaceholder.typicode.com/posts", options);

//     let response = await p;
//     let response2 = await response.json();
//     console.log(response2);

// }

// data();




// async function data() {

//     let p = fetch("https://jsonplaceholder.typicode.com/posts", {
//         method: "POST",

//         headers: { "content-type": "application/json" },

//         body: JSON.stringify({
//             title: 'games',
//             gameName: 'FreeFire',
//             userName: 'Prashant'
//         }),
//     });

//     try {
//         console.log("getting data...")
//         let response = await p;
//         let response2 = await response.json();
//         console.log(response2);
//     }

//     catch (error) {
//         console.log(error);
//     }

//     finally {
//         console.log("Done!")
//     }
// }

// data(); 




function data(userName) {

    console.log("getting data...")

    let p = fetch("https://jsonplaceholder.typicode.com/posts", {

        method: "POST",

        headers: { "content-type": "application/json" },

        body: JSON.stringify({
            title: 'games',
            gameName: 'FreeFire',
            userName: `${userName}`
        }),
    });

    return p;
}

async function getdata() {
    try {
        let response = await data('Prashant');
        let response2 = await response.json();
        console.log(response2);
    }

    catch (error) {
        console.log(error);
    }

    finally {
        console.log("Done!")
    }

    try {
        let response = await data('Vishal');
        let response2 = await response.json();
        console.log(response2);
    }

    catch (error) {
        console.log(error);
    }

    finally {
        console.log("Done!")
    }

    try {
        let response = await data('Piyush');
        let response2 = await response.json();
        console.log(response2);
    }

    catch (error) {
        console.log(error);
    }

    finally {
        console.log("Done!")
    }

    try {
        let response = await data('Ayush');
        let response2 = await response.json();
        console.log(response2);
    }

    catch (error) {
        console.log(error);
    }

    finally {
        console.log("Done!")
    }
}

getdata();